// Code generated by mmsgen; DO NOT EDIT.

package mms

import (
	"sort"
	"sync"
)

// Int64sCache of slices
type Int64sCache struct {
	mutex sync.RWMutex
	ps    []poolInt64sCache
}

type poolInt64sCache struct {
	p    *sync.Pool
	size int
}

// Get return slice
func (c *Int64sCache) Get(size int) []int64 {
	// lock
	c.mutex.Lock()
	defer func() {
		c.mutex.Unlock()
	}()

	// finding index
	index := c.index(size)

	// creating a new pool
	if index < 0 {
		c.ps = append(c.ps, poolInt64sCache{
			p: &sync.Pool{
				New: func() interface{} {
					return make([]int64, size)
				},
			},
			size: size,
		})
		// sort
		sort.SliceStable(c.ps, func(i, j int) bool {
			return c.ps[i].size < c.ps[j].size
		})

		// return
		index = c.index(size)
		return c.ps[index].p.New().([]int64)
	}

	// pool is found
	arr := c.ps[index].p.Get().([]int64)

	// Only for debugging:
	//	if len(arr) < size {
	//		panic(fmt.Errorf("not same sizes: %d != %d", len(arr), size))
	//	}

	for i := range arr {
		// initialization of slice
		arr[i] = 0
	}
	return arr
}

// Put slice into pool
func (c *Int64sCache) Put(arr []int64) {
	c.mutex.RLock() // lock
	var (
		size  = cap(arr)
		index = c.index(size) // finding index
	)
	c.mutex.RUnlock() // unlock

	if index < 0 {
		// pool is not exist
		return
	}

	// lock and add
	c.mutex.Lock()
	if index < len(c.ps) && c.ps[index].size == size {
		c.ps[index].p.Put(arr)
	}
	c.mutex.Unlock()
}

// return index with excepted size
func (c *Int64sCache) index(size int) int {
	index := -1
	for i := range c.ps {
		if c.ps[i].size < size {
			continue
		}
		if c.ps[i].size == size {
			index = i
		}
		break
	}
	return index
}
